---
name: Crossfire Server Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  crosfire_server_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
      PORT: 13327
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          apt update
          apt install -y crossfire-server
      - name: Run Tests
        run: |
          /usr/bin/true
